### ISSUE TITLE
Question about RPN and background embedding

### ISSUE THREAD

**Issue by GoGoDuck912** [alirezazareian/ovr-cnn#6]
Thank you for sharing the nice work!
Here I have two main questions about some implementation details,
1. How could RPN network propose bboxes for novel classes? Generally speaking, the RPN network tells foreground(all base classes) from the background and is trained only on base classes. If trained on base classes, the RPN network may fail to propose the bboxs candidates of novel classes. Any special treatment to solve this issue?
2. About the all-zero background embedding. Will the cosine similarities between classes be negative values? If not, it will never classify the ROI into background class when it is set all zeros.

**Comment by alirezazareian** [comment]
Thank you for your great questions.
1.  You are right, the target classes are unseen during the training of the RPN model, and hence there is no guarantee that RPN will recognize target classes in test time. However, since we treat all base classes as a single positive class for the RPN, we can hope that it will learn their common "objectness" property and can generalize that property to unseen classes as well. In fact, when we evaluate the RPN that is trained on base classes, we observe that its performance is quite good on target classes as well, without any special trick. More specifically, our RPN achieves 40% Recall@100 on base classes, while it achieves 30% on target classes. Despite the 10% gap, it is still an acceptable performance for real-world applications. Furthermore, there are a group of papers [1, 2] that try to improve zero-shot object proposal, which we discussed briefly in the related work of our paper, but did not utilize in this work.
2. We use dot product rather than cosine similarity, which resembles the linear classifier commonly used in Faster R-CNN, and hence the similarity values can be negative.

[1] Zhu, Pengkai, Hanxiao Wang, and Venkatesh Saligrama. "Zero shot detection." IEEE Transactions on Circuits and Systems for Video Technology 30.4 (2019): 998-1010.
[2] Zhu, Pengkai, Hanxiao Wang, and Venkatesh Saligrama. "Don't Even Look Once: Synthesizing Features for Zero-Shot Detection." Proceedings of the IEEE/CVF Conference on Computer Vision and Pattern Recognition. 2020.

**Comment by GoGoDuck912** [comment]
Thanks for your quick reply.
